namespace: app

replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/gke-lab-474404/apps/hello
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
