namespace: app

replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/gke-lab-474404/apps/hello
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  annotations:
    cloud.google.com/neg: '{"ingress": true}'

ingress:
  enabled: true
  className: gce
  host: your.domain.example        # <-- set DNS you control (A/AAAA → Ingress IP)
  tls:
    enabled: true
    managedCertName: hello-cert


resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
