{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello
  annotations:
    {{- if and .Values.ingress.tls.enabled .Values.ingress.tls.managedCertName }}
    networking.gke.io/managed-certificates: {{ .Values.ingress.tls.managedCertName | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello
            port:
              number: {{ .Values.service.port }}
{{- end }}
