apiVersion: v1
kind: Service
metadata:
  name: hello
  labels: { app: hello }
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hello
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
